initialization:
  method: generate # or load
  generate:
    method: random # or poisson
    num_of_fibres: 200
    poisson_radius: 0.55
    resolution: 30
    fibre_r_initial: 0.1
    domain_size_initial: [10.0, 10.0, 10.0]
    angle_std_dev: 0.05
  load:
    name: test_run
    step: 0

spring_system:
  k_length: 0.1
  k_curvature: 0.1
  k_boundary: 1.0
  k_overlap: 100.0

evolution:
  max_iterations: 500000
  fibre_r_target: 0.25
  fibre_r_steps: 30
  fibre_r_std: 0.025
  domain_size_target: [8.0, 8.0, 10.0]
  domain_size_steps: 20
  overlap_threshold: 0
  apply_pbc: True

optimization:
  joint_optimizer: adam # adam or lbfgs
  learning_rate: 0.01
  grad_clipping: False
  max_grad_norm: 1.0
  # line loss converges better with alternating phases
  line_loss: True
  alternate_phases: True
  overlap_optimizer: sgd # sgd or own
  max_iter_per_phase: 2000 # for the joint loss optimization
  cumulative_loss_threshold: 0.01
  moving_average_window: 300
  reset_optimizers: False

stats:
  to_plot: True
  logging_freq: 100
